module(
    name = "lvgl",
    version = "9.5.0",
)

bazel_dep(name = "googletest", version = "1.17.0.bcr.2")
bazel_dep(name = "openssl", version = "3.5.5.bcr.4")
bazel_dep(name = "libx11", version = "1.8.12.bcr.5")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "apple_support", version = "2.3.0")
bazel_dep(name = "rules_cc", version = "0.2.18")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_cc_autoconf", version = "0.12.1")
bazel_dep(name = "sdl2", version = "2.32.0.bcr.beta.5")
bazel_dep(name = "harfbuzz", version = "14.1.0")
bazel_dep(name = "freetype", version = "2.14.1")

cc_configure = use_extension("@rules_cc//cc:extensions.bzl", "cc_configure_extension")
use_repo(cc_configure, "local_config_cc")
